project:
  type: website
  output-dir: _site

website:
  title: "FISHEyE"
  page-navigation: true
  navbar:
    search: FALSE
    logo: "www/images/noaalogo.png"
    pinned: FALSE
    right:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: literature.qmd
        text: "Literature"
      - href: resources.qmd
        text: "Resources"
      - href: contact.qmd
        text: "Contact"
  page-footer:
    left: "&copy; NOAA Fisheries 2025"

format:
  html:
    theme:
      - cosmo
      - styles.scss
    fontsize: 1.1em
    mainfont: Montserrat
    google-fonts:
      - Montserrat
    toc: FALSE




