project:
  type: website

website:
  title: "FisheYe"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: literature.qmd
        text: Literature
      - href: resources.qmd
        text: Resources
      - href: contact.qmd
        text: Contact
  page-footer:
    left: Copyright 2025, NOAA

format:
  html:
    theme:
      - cosmo
      - styles.scss
    fontsize: 1.1em
    css: styles.css
    toc: FALSE



